"""Change game_complete to game_status enum

Revision ID: 58ada70297c9
Revises: 626a04504140
Create Date: 2024-06-30 12:00:13.802207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ada70297c9'
down_revision: Union[str, None] = '626a04504140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stinkers', sa.Column('game_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE', name='gamestatus'), nullable=False))
    op.drop_column('stinkers', 'game_complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stinkers', sa.Column('game_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('stinkers', 'game_status')
    # ### end Alembic commands ###
